[김가람휘] Feature/planetlistview test
wecode-bootcamp-korea/30-2nd-Starfolio-backend pull request #11
Opened 2022-03-19 08:43 UTC by kimkaramhwi

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- planetlistview get 메소드 테스트 코드 작성

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 기본리스트, 필터별, 정렬별 성공 테스트 코드 작성
2. 체크인날짜가 체크아웃날짜보다 느릴 때 실패하는 테스트 코드 작성

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

<br />

## :: 기타 질문 및 특이 사항

2022-03-20 05:08 UTC, kyeongraekim requested changes

2022-03-20 05:08 UTC, kyeongraekim commented on planets/tests.py
> +    def test_planetlistview_get_success_filter(self):
전체적인 테스트코드 함수명 네이밍을 test_success / test_fail 로 시작하면 더 읽히기 쉬울 것 같네요!~

2022-03-20 05:08 UTC, kyeongraekim commented on planets/tests.py
> +        Accomodation.objects.create(
같은 성질의 같은 객체에 여러 데이터를 넣을 때 그냥 create 말고 bulk_create를 자주 사용합니다. 해당 개념을 리서치해서 비록 적은 데이터 수지만 한 번 적용해보세요!~

2022-03-20 06:29 UTC, kimkaramhwi commented on planets/tests.py
> +    def test_planetlistview_get_success_filter(self):
넵 수정했습니다!

2022-03-20 06:49 UTC, kimkaramhwi commented on planets/tests.py
> +        Accomodation.objects.create(
네 적용해보겠습니다!

2022-03-21 02:31 UTC, kyeongraekim requested changes

2022-03-21 02:31 UTC, kyeongraekim commented on planets/tests.py
> +            '/planets?check_in=2022-03-19&check_out=2022-03-18'
이 부분도 프론트 측에 큰 무리가 가지 않는다면 언더바 말고 하이픈으로 한 번 진행해보세요!~

2022-03-21 04:44 UTC, kimkaramhwi commented on planets/tests.py
> +            '/planets?check_in=2022-03-19&check_out=2022-03-18'
넵 알겠습니다~!

2022-03-21 06:43 UTC, kyeongraekim approved these changes
LGTM!~

2022-03-21 06:43 UTC, merged