[박건규] 소셜로그인 기능 추가
wecode-bootcamp-korea/30-2nd-Starfolio-backend pull request #4
Opened 2022-03-16 09:30 UTC by Pbang91

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [x] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 카카오 소셜로그인 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 소셜로그인 구현(카카오)
- 전달받은 토큰으로 해당 user의 kakao_id 회신 확인
- 기존 회원인 경우와 신규 회원인 경우에 따른 응답 분기 처리
- 우리 클라이언트 로그인 성공 시 우리 토큰 전달 및 로그인 데코레이터 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 소셜로그인을 동작하게 하는 OAuth에 대해서 공부할 수 있었습니다.
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항
- 꼭 프론트쪽에서 토큰을 받는 것이 아닌, 백서버쪽에서 인가 코드 및 인가 토큰을 받아올 수 없는지 궁금합니다. redirect를 이용해서 하면 cors 관련 에러가 발생하지 않는지도 궁금합니다.

2022-03-16 10:32 UTC, kyeongraekim requested changes
아래 내용 확인하여 수정해주세요!~

2022-03-16 10:32 UTC, kyeongraekim commented on users/urls.py
> +    path('/kakao_login', KakaoLogInView.as_view()),
RESTful 한 작성을 위해서 언더바 말고 하이픈을 이용해주세요~

2022-03-16 10:32 UTC, kyeongraekim commented on users/utils.py
> +                return JsonResponse({"message" : "DOES_NOT_AUTHORIZATION"}, status = 401)
does not authorization이라는 말이 영문법상 어색하게 들리네요!~

2022-03-16 10:32 UTC, kyeongraekim commented on users/views.py
> +            user_info_response = requests.get(kakao_user_info_api, headers={'Authorization' : f'Bearer {kakao_access_token}'}).json()
requests 모듈을 사용하실 때에는 timeout 옵션을 반드시 설정해주셔야 합니다.
그 이유는 timeout option을 추가하지 않으면 서버의 응답을 계속해서 기다리고 있는 문제가 발생 합니다. timeout 옵션을 추가해 주세요.

예시
```python
class KakaoLoginView(View):
    def post(self, request):
        try:
            kakao_access_token    = request.headers['Authorization']
            kakao_user_api_url    = '<https://kapi.kakao.com/v2/user/me>'
            headers     = {"Authorization": f"Bearer ${kakao_access_token}"}

            response = requests.get(kakao_user_api_url, headers = headers, timeout = ..)

2022-03-16 10:32 UTC, kyeongraekim commented on users/views.py
> +            print(kakao_access_token)
디버깅에 사용된 print문은 푸시 전에 꼭 삭제를 해주세요! 실제로 상용화 될 서비스상의 코드라고 생각해주세요!

2022-03-16 10:32 UTC, kyeongraekim commented on users/utils.py
> +            return JsonResponse({"message" : "KEY_ERROR IN DECO"}, status = 400)
DECO라는 영어표현의 의미가 많이 생략되어 보여서 클라이언트측에서 메세지를 받았을 때 혼선을 줄 수 있어 보이네요!

2022-03-16 10:32 UTC, kyeongraekim commented on users/views.py
> +            if create:
is_created 가 더 가독성이 좋은 표현일 것 같아 보입니다~

2022-03-16 10:32 UTC, kyeongraekim commented on users/views.py
> +            access_token = jwt.encode({'user_id' : user.id}, SECRET_KEY, ALGORITHM)
키 값에 해당되는 user_id 부분을 그냥 id로 적어주는게 보안성을 조금이나마 향상시킬 수 있는 방법이곘네요!~

2022-03-16 11:04 UTC, Pbang91 commented on users/urls.py
> +    path('/kakao_login', KakaoLogInView.as_view()),
하이픈으로 수정했습니다.

2022-03-16 11:04 UTC, Pbang91 commented on users/utils.py
> +                return JsonResponse({"message" : "DOES_NOT_AUTHORIZATION"}, status = 401)
No authorization 으로 변경했습니다.

2022-03-16 11:04 UTC, Pbang91 commented on users/views.py
> +            user_info_response = requests.get(kakao_user_info_api, headers={'Authorization' : f'Bearer {kakao_access_token}'}).json()
Timeout을 2초로 설정했습니다.

2022-03-16 11:05 UTC, Pbang91 commented on users/views.py
> +            print(kakao_access_token)
삭제했습니다. 죄송합니다!

2022-03-16 11:05 UTC, Pbang91 commented on users/utils.py
> +            return JsonResponse({"message" : "KEY_ERROR IN DECO"}, status = 400)
KEY ERROR 로 통일하였습니다!

2022-03-16 11:05 UTC, Pbang91 commented on users/views.py
> +            access_token = jwt.encode({'user_id' : user.id}, SECRET_KEY, ALGORITHM)
넵 수정했습니다.

2022-03-17 02:53 UTC, kyeongraekim requested changes

2022-03-17 02:53 UTC, kyeongraekim commented on users/utils.py
> +                return JsonResponse({"message" : "INVALID_UESR"}, status = 401)
가독성을 위해서 이 부분은 User.DoesNotExist로 exception을 통해서 에러 관리를 하는 것이 어떨까요?

2022-03-17 02:53 UTC, kyeongraekim commented on users/views.py
> +            return JsonResponse({'message' : 'SUCCESS', 'access_token' : access_token}, status = 200)
ux적/클라이언트적 관점에서는 카카오 소셜 로그인 버튼을 누른 이후 회원가입이 아닌 로그인이 된 내용으로 받아들여지게 됨으로 if 문 분기를 굳이 지정 안해주셔도 될것 같네요!~ 즉 전체적으로 로그인이 되는 과정이며 회원가입도 백엔드선에서만 관리되어지는 절차로 이해하시면 편하실 것 같습니다~

2022-03-17 05:02 UTC, Pbang91 commented on users/utils.py
> +                return JsonResponse({"message" : "INVALID_UESR"}, status = 401)
네 except 구문으로 빼줬습니다!

2022-03-17 05:02 UTC, Pbang91 commented on users/views.py
> +            return JsonResponse({'message' : 'SUCCESS', 'access_token' : access_token}, status = 200)
넵 하나로 통일해서 전달해주도록 수정했습니다.

2022-03-17 05:29 UTC, kyeongraekim approved these changes
LGTM!~ 이제 테스트 브랜치를 따로 파주셔서 해당 내용에 대한 테스트 코드 푸시해주세요!~

2022-03-17 05:29 UTC, merged