[김가람휘] feature/bookings-post
wecode-bootcamp-korea/30-2nd-Starfolio-backend pull request #7
Opened 2022-03-18 04:40 UTC by kimkaramhwi

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- bookingsview-post 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1.  디테일에서 숙소의 가능한 날짜를 필터링해서 예약으로 들어오므로 날짜를 필터링 할 필요는 없고 유저가 다른 숙소에 예약한 날짜가 겹치는 경우 이미 예약이 존재한다고 오류를 리턴했습니다.
2.  리스트에서 인원 수를 필터링해서 들어오지 않는 경우 예약창에서 어른과 아이의 수를 고른 후 숙소를 예약하므로 인원 수가 그 숙소의 최대 인원 수를 넘을 경우 오류를 리턴했습니다.
3.  해당 숙소의 기준 인원을 넘길 경우 인원 한명 당 임의의 가격을 추가할 수 있도록 했습니다.

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

<br />

## :: 기타 질문 및 특이 사항

2022-03-18 06:38 UTC, kyeongraekim requested changes
아래 내용 참고하여 수정해주세요!~

2022-03-18 06:38 UTC, kyeongraekim commented on bookings/tests.py
> +                'pric'               : 10000,
가격 부분 오타가 있는 것 같아요~

2022-03-18 06:38 UTC, kyeongraekim commented on bookings/tests.py
> +class BookingTest(TestCase):
테스트 코드는 간단한 성공, 실패 코드 말고 실제로 내가 의도한 모든 에러 핸들링 처리들이 잘 작동하는지 ux적 관점에서 진행해주셔야 해요~ View 선에서 if문으로 처리한 에러들도 모두 assert 일치 여부를 판단할 수 있게 테스트 함수를 더 만들어 주세요~

2022-03-18 06:38 UTC, kyeongraekim commented on bookings/tests.py
> +    def setUp(self):
장고에서는 테스트용 메소드로 setUp외에 setUpTestData라는 것도 있습니다. 둘의 차이를 비교해보고 해당 테스트 코드에서 어떠한 내용을 사용하는 것이 나을지 한 번 고민해보세요!~ 그리고 결정사항을 아래 코멘트로 남겨주세요~

2022-03-18 06:38 UTC, kyeongraekim commented on bookings/views.py
> +                total_price = price + (num_of_people-accomodation.min_of_people)*100000
해당 부분 좀 전에 말씀 나눈 것 처럼 백엔드 차원에서 최대한 상용 웹서비스에 가까운 로직을 한 번 도전해보세요!

그리고 디테일 뷰에서 제한이 되어서 클라이언트 측에 디스플레이 되어서 원치않는 형태의 request가 안들어 올 수 있다고 판단될 수 있겠으나, 예약 View에서 최종적으로 더 제한하는 로직을 걸어주면 더 좋은 코드가 될 수 있곘네요!

2022-03-18 11:51 UTC, kimkaramhwi commented on bookings/tests.py
> +                'pric'               : 10000,
key_error test를 작성하고 싶었는데 굳이 키에러 테스트 코드는 작성할 필요가 없는 것 같네요! ux적 관점으로 에러코드를 작성해서 다시 올렸습니다!

2022-03-18 11:51 UTC, kimkaramhwi commented on bookings/tests.py
> +class BookingTest(TestCase):
네 알겠습니다!

2022-03-18 11:51 UTC, kimkaramhwi commented on bookings/views.py
> +                total_price = price + (num_of_people-accomodation.min_of_people)*100000
수정했습니다!

2022-03-18 12:09 UTC, kimkaramhwi commented on bookings/tests.py
> +    def setUp(self):
setUp은 method 마다 test 데이터셋을 만들어주고 setUpTestData은 TestCase 한개마다 (class 마다) 초기 데이터 test 데이터를 만들어준다고 합니다 따라서 setUpTestData가 더 효율적이므로 setUpTestData를 사용했습니다.

2022-03-20 04:07 UTC, kyeongraekim requested changes

2022-03-20 04:07 UTC, kyeongraekim commented on bookings/tests.py
> +                'pric'               : 10000,
아하 그러한 의도이셨다면 의도하신 상황이 어떠한 내용이었는지 테스트 함수명에 정확히 명시하는 모습이 더 올바른 형태일 것 같네요~ 

현재 작성해주신 "test_bookingview_post_error" 보다는 "test_fail_to_reserve_room_without_booking_price_information" 정도로 내가 일부러 일으킨 에러사항에 대한 원인 요소들을 함수 제목에 명시해주세요~

2022-03-20 04:40 UTC, kyeongraekim commented
가장 최근에 올라온 PR이 최신 booking PR로 보여지는데 지금이 PR은 closing 해도 될까요?

2022-03-22 04:57 UTC, closed without merging