[박건규] feat: Add planet detail api
wecode-bootcamp-korea/30-2nd-Starfolio-backend pull request #8
Opened 2022-03-18 05:01 UTC by Pbang91

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 상품 디테일 api 구현(리스트 api에서 날짜 지정 후 전달 or 미지정 후 전달)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 플래닛 디테일 api 구현
- 쿼리파라미터로 해당 플래닛과 숙소, 체크인, 체크아웃 설정을 받아줄 수 있도록 코드 작성
- 체크인, 체크아웃 미설정시 해당 디테일 페이지에서 설정후 숙소의 정보를 재전달하도록 구현
- 테스트 방법 : 쿼리파라미터 입력 후 datail  이동 or 미입력 후 detail 이동

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 유닛테스트의 중요성을 알 수 있었습니다.

<br />

## :: 기타 질문 및 특이 사항
- 쿼리 최적화를 진행하고 있습니다.

2022-03-18 08:18 UTC, kyeongraekim requested changes

2022-03-18 08:18 UTC, kyeongraekim commented on planets/tests.py
> +    def get_invalid_accomodation_test_planetdetail(self):
- 실패하는 테스트에 대한 코드임으로 위 테스트 코드 함수명처럼 test_fail_.. 으로 네이밍을 통일 시켜 주세요~

- 그리고 실제 어떠한 상황에서 성공하고 실패는 함수인지 명시해주세요~
예시) test_fail_to_login_when_kakao_token_is_invalid

2022-03-18 08:18 UTC, kyeongraekim commented on planets/views.py
> +                'unvalid_date'      : unvalid_date
unvalid 부분에 오타가 들어간 것 같네요~ 찾아보니 오타는 아니긴한데 invalid가 훨씬 많이 쓰이는 표현으로 보여지네요

2022-03-18 08:18 UTC, kyeongraekim commented on planets/views.py
> +    def get(self, request):
detail view 이니 path_parameter로 숙소 아이디와 planet아이디를 받아오면 좋을 것 같네요~

2022-03-18 08:18 UTC, kyeongraekim commented on planets/views.py
> +                'num_of_bed'        : accomodation.num_of_bed,
data key값들 혹시 가람님과 동일하게 잘 맞추어졌는지 한 번 확인해주세요!~

2022-03-18 08:18 UTC, kyeongraekim commented on planets/tests.py
> +        )
View 파일에 if문으로 분기되어 있는 내용들도 의도에 맞게 잘 작동하는지 새로운 테스트 코드들을 추가해주셔야 될 것 같네요!~

그리고 클라이언트/사용자 입장에서 나올 수 있는 모든 경우의 수를 잘 확인하여 실패코드도 한 번 고민해주세요!~

2022-03-18 11:39 UTC, Pbang91 commented on planets/tests.py
> +    def get_invalid_accomodation_test_planetdetail(self):
넵 테스트 코드 함수명 변경했습니다.

2022-03-18 11:40 UTC, Pbang91 commented on planets/views.py
> +                'unvalid_date'      : unvalid_date
invalid 로 변경했습니다.

2022-03-18 11:40 UTC, Pbang91 commented on planets/views.py
> +    def get(self, request):
패스 파라미터로 받아줄 수 있게 수정했습니다.

2022-03-18 11:40 UTC, Pbang91 commented on planets/views.py
> +                'num_of_bed'        : accomodation.num_of_bed,
중복되는 키값을 동일한 변수명으로 맞추었습니다.

2022-03-18 11:40 UTC, Pbang91 commented on planets/tests.py
> +        )
추가 테스트 코드 작성했습니다!

2022-03-20 04:36 UTC, kyeongraekim requested changes

2022-03-20 04:36 UTC, kyeongraekim commented on planets/tests.py
> +    def test_fail_invalid_check_out_date_planet_detail(self):
함수 명 뒤에 전반적으로 붙어있는 planet_detail이라는 단어들이 다소 verbose하게 느껴집니다. 해당 부분들을 지워주세요~

test_fail_room_reservation_with_invalid_check_out_date 정도가 어떠한 상황에서 어떠한원인으로 일어날 수 있는 에러인지가 명시가되어서 보다 올바른 함수명 같습니다!~ 개발자들은 늘 또다른 개발자들을 위해서 한번에 파악하기 쉬운 네이밍을 작성해주셔야함을 명심해주세요~

나머지 테스트 코드 함수명들도 한 번 재고하여서 전체적으로 수정해주세요~

2022-03-20 04:36 UTC, kyeongraekim commented on planets/views.py
> +                invalid_date += [datetime.strftime(booking.start_date+timedelta(days=i), "%Y-%m-%d") for i in range(nights)]
상용화된 웹서비스 코드에 있어서 i와 같은 모호한 변수명은 사용을 지양해주셔야 합니다. 보다 올바른 변수명이 어떤게 있을까요?

2022-03-20 04:36 UTC, kyeongraekim commented on planets/tests.py
> +        booking_number = uuid.uuid1()
uuid1과 4의 차이는 다음의 문제가 있습니다. 현재 프로젝트 선에서는 따라서 uuid4 사용을 권장드려요. 아래의 내용외에도 어떠한차이가 더 있는지 한 번 리서치 해보세요!~

uuid1(): 컴퓨터네트워크주소와 현재시간으로 UUID를 생성한다. 네트워크주소 노출에 주의해야한다.
uuid4(): 랜덤하게 UUID를 생성한다.

2022-03-20 04:36 UTC, kyeongraekim commented on planets/views.py
> +            }
중복된 모습의 코드들이 보이네요. 삼항연산자를 사용하여서 하나의 data 값을 보내주시되, 없는 내용들은 None이 반환되게 설정할 수는 없을까요?

2022-03-20 08:50 UTC, Pbang91 commented on planets/tests.py
> +    def test_fail_invalid_check_out_date_planet_detail(self):
전체적인 함수명을 다시 한번 정리했습니다.

2022-03-20 08:50 UTC, Pbang91 commented on planets/views.py
> +                invalid_date += [datetime.strftime(booking.start_date+timedelta(days=i), "%Y-%m-%d") for i in range(nights)]
i -> night 로 변경했습니다.

2022-03-20 08:50 UTC, Pbang91 commented on planets/tests.py
> +        booking_number = uuid.uuid1()
넵

2022-03-20 08:51 UTC, Pbang91 commented on planets/views.py
> +            }
기본 data에서 condition에 따른 값을 추가하였습니다.

2022-03-21 02:07 UTC, kyeongraekim requested changes

2022-03-21 02:07 UTC, kyeongraekim commented on planets/tests.py
> +            id                 = 2,
해당부분은 booking이라는 동일 모델 클래스 테이블에 들어가는 같은 성질의 데이터 객체들이니 bulk_create를 써서 한번에 데이터를 넣어주세요~

2022-03-21 02:07 UTC, kyeongraekim commented on planets/views.py
> +                return JsonResponse({'result' : data}, status = 200)
해당 부분에 해당하는 내용을 따로 모듈화로 빼보는 것은 어떨까요? 같은 view안의 함수안에 있으니 로직이 조금 수월하게 읽히는 것 같지가 않네요!~ 
check_valid_date() 정도의 함수를 새로 만들어서 import하여서 적용해주시면 좋을 것 같습니다~

2022-03-21 02:08 UTC, kyeongraekim requested changes

2022-03-21 02:08 UTC, kyeongraekim commented on planets/tests.py
> +    def setUp(self):
setUp test외에 적용가능한 setUpTestData도 한 번 리서치후 어떤 이점이 있을지 고민해보시고 적용 여부를 새로 판단해주세요!~

2022-03-21 15:49 UTC, Pbang91 commented on planets/tests.py
> +            id                 = 2,
넵

2022-03-21 15:50 UTC, Pbang91 commented on planets/views.py
> +                return JsonResponse({'result' : data}, status = 200)
넵 모듈화 진행했습니다.

2022-03-21 15:50 UTC, Pbang91 commented on planets/tests.py
> +    def setUp(self):
넵

2022-03-22 02:58 UTC, kyeongraekim requested changes

2022-03-22 02:58 UTC, kyeongraekim commented on planets/views.py
> +
해당 View에 대한 최종리턴은 모듈화된 함수가 아닌 이곳 클래스에서 이루어지도록 변경해주세요!~

2022-03-22 05:06 UTC, Pbang91 commented on planets/views.py
> +
넵 utils 에서 데이터를 전달하여 해당 클래스에서 Json으로 리턴하는 방법으로 변경했습니다.

2022-03-23 05:43 UTC, kyeongraekim commented
구두로 전달드린 내용 수정 하시고 푸시해주세요~

2022-03-23 07:18 UTC, kyeongraekim approved these changes

2022-03-23 07:18 UTC, kyeongraekim commented on planets/utils.py
> +        stays        = (booking.end_date - booking.start_date).days
이곳도 정렬 한 번 신경써 주세요!~

2022-03-23 07:19 UTC, merged