[김가람휘]feature/bookings
wecode-bootcamp-korea/30-2nd-Starfolio-backend pull request #9
Opened 2022-03-18 11:49 UTC by kimkaramhwi

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- bookings -> post, get, patch, delete 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 예약 post, get, patch, delete 구현
2. 예약뷰 unit test code 작성

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

<br />

## :: 기타 질문 및 특이 사항
- uuid 테스트 방법이 맞는지 궁금합니다.

2022-03-18 12:55 UTC, kyeongraekim requested changes
전반적으로 깔끔하게 잘 작성해주셨는데 마이너한 접근으로 다음의 내용 한 번더 고민해서 수정 반영해주세요!~

2022-03-18 12:55 UTC, kyeongraekim commented on bookings/views.py
> +            surcharge_rate     = 0.1
상수데이터는 파이썬 컨벤션상 대문자로 처리해주세요!~

2022-03-18 12:55 UTC, kyeongraekim commented on users/migrations/0003_remove_user_planets.py
> +    ]
깃허브에 올라오는 코드는 실제 상용화된 서비스에 접목될 코드라고 생각해주시고 그 무게감을 꼭 유념해주세요! 이러한 주석처리된 코드는 절대 올라와서는 안됩니다!~

2022-03-18 12:55 UTC, kyeongraekim commented on bookings/views.py
> +            q &= Q(start_date__lt=today)
해당부분에(90-94라인 코드) 대한 비즈니스 로직 부분 관련 의도하신 내용을 아래 코멘트로 설명남겨주세요!~

2022-03-19 01:06 UTC, kimkaramhwi commented on bookings/views.py
> +            surcharge_rate     = 0.1
네 알겠습니다

2022-03-19 01:29 UTC, kimkaramhwi commented on users/migrations/0003_remove_user_planets.py
> +    ]
네 알겠습니다 마이그레이션 수정해서 브랜치 새로 올리겠습니다!

2022-03-19 01:41 UTC, kimkaramhwi commented on bookings/views.py
> +            q &= Q(start_date__lt=today)
스테이폴리오 마이페이지에서 예약정보화면에 예약정보와 다녀온 스테이 이렇게 두개의 카테고리가 있습니다.
따라서 예약한 날짜가 아직 지나지 않았을 경우 예약정보에 예약한 날짜가 지났을 경우 다녀온 스테이에 예약정보가 뜰 수 있게 구성했습니다.

2022-03-20 04:52 UTC, kyeongraekim requested changes

2022-03-20 04:52 UTC, kyeongraekim commented on bookings/views.py
> +            q &= Q(start_date__lt=today)
클라이언트 측으로부터 쿼리 스트링으로 받을 내용은 그렇다면 RESTful 하게 작성해주심을 권장드립니다~ 아래의 내용 참고해주세요!

![Screen Shot 2022-03-20 at 1 51 44 PM](https://user-images.githubusercontent.com/73090474/159148737-e3f25d5b-84f1-4f45-bece-c4cc9b19e490.png)

2022-03-20 04:58 UTC, kyeongraekim requested changes

2022-03-20 04:58 UTC, kyeongraekim commented on bookings/views.py
> +            number_of_children = int(data['number_of_children'])
이곳도 프론트에서 건너올 쿼리스트링 데이터에 한해서는 언더바 사용보다는 하이픈을 사용해주세요~

2022-03-20 04:58 UTC, kyeongraekim commented on bookings/views.py
> +            q &= Q(start_date__lt=today)
아하 그런 로직이었군요 넵 알겠습니다 이해했습니다!~

2022-03-20 07:23 UTC, kimkaramhwi commented on bookings/views.py
> +            q &= Q(start_date__lt=today)
네 수정했습니다!

2022-03-20 08:00 UTC, kimkaramhwi commented on bookings/views.py
> +            number_of_children = int(data['number_of_children'])
넵 알겠습니다!

2022-03-21 02:28 UTC, kyeongraekim requested changes
아래 마이너한 부분에 대한 코멘트 부탁드립니다~ 그러면 예약뷰는 문제 없어 보입니다!~

2022-03-21 02:28 UTC, kyeongraekim commented on bookings/views.py
> +        booking_ids = request.GET.get('booking-ids').split(',')
이 부분은 어떤 형태로 booking-id 값들을 리스트로 받기로 하신 것 같은데 맞으실까요? 장고에서 제공하는 getlist() 메소드의 사용 불가여부를 혹시 이전에 판단해주셨다면 관련 내용을 아래에 코멘트로 남겨주세요~

2022-03-21 04:39 UTC, kimkaramhwi commented on bookings/views.py
> +        booking_ids = request.GET.get('booking-ids').split(',')
getlist를 까먹고 있었습니다 쿼리파라미터를 getlist로 받는 방식으로 수정했습니다~

2022-03-21 05:32 UTC, kyeongraekim approved these changes
LGTM!~

2022-03-21 05:32 UTC, merged